# Jekyll configuration with alternative directory structure
# _config.yml

# Base URL and GitHub Pages URL
baseurl: "/Portfolio.io"
url: "https://adwaitsv1.github.io"

# Site settings
title: "Portfolio Website"
description: "Personal portfolio and project showcase"
author: "Adwait"

# Important: Tell Jekyll where to find your pages
source: .
destination: ./_site
layouts_dir: templates
includes_dir: templates/includes # If you have includes

# Tell Jekyll which file to use as index
# This makes templates/index.html your homepage
# Note: This is non-standard and may cause issues
index_page: templates/index.html

# Markdown processor
markdown: kramdown

# Permalinks settings
permalink: /:categories/:year/:month/:day/:title/

# Exclude files/folders from being processed by Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - Procfile
  - requirements.txt
  - runtime.txt
  - .jekyll-cache
  - app.py
  - .gitignore
  - .DS_Store

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Theme settings
theme: jekyll-theme-primer

# Include the custom CSS and JavaScript
sass:
  sass_dir: static/css
  style: compressed

# Asset paths
assets:
  css: "/static/css/style.css"
  js: "/static/js/script.js"
  images: "/static/images"