# _config.yml
# Jekyll configuration for your portfolio website

# Base URL and GitHub Pages URL
baseurl: "/Portfolio-Website"  # Updated to match your repository's name (based on folder structure)
url: "https://adwaitsv1.github.io"  # the URL of your GitHub Pages

# Site settings
title: "Portfolio Website"
description: "Personal portfolio and project showcase"
author: "Adwait"

# Markdown processor (Kramdown is the default)
markdown: kramdown

# Permalinks settings
permalink: /:categories/:year/:month/:day/:title/

# Exclude files/folders from being processed by Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - Procfile
  - requirements.txt
  - runtime.txt
  - .jekyll-cache
  - app.py
  - .gitignore
  - .DS_Store

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Theme settings
theme: jekyll-theme-primer  # Or choose any other theme you prefer
defaults:
  - scope:
      path: ""
    values:
      layout: "default"  # Set the layout that you want for all pages

# Include the custom CSS and JavaScript
sass:
  sass_dir: static/css
  style: compressed

# Asset paths
assets:
  css: "/static/css/style.css"
  js: "/static/js/script.js"
  images: "/static/images"

# Collections (if you have any)
collections:
  projects:
    output: true
    permalink: /projects/:name/